# Laboratorium 4 — NumPy zaawansowane
**Autor:** Dominika Wrześniewska

In [1]:
import numpy as np

Ćwiczenie 1: Broadcasting — zastosowania biznesowe (20
min)
Cel
Użyj broadcastingu do obliczeń na danych o różnych kształtach. Każde zadanie
w osobnej komórce z komentarzem.

In [2]:
# Ceny 4 produktów w 3 sklepach
ceny = np.array([[29.99, 31.99, 28.99],
[49.99, 52.99, 47.99],
[14.99, 15.99, 13.99],
# Produkt A
# Produkt B
# Produkt C
[99.99, 104.99, 94.99]]) # Produkt D
sklepy = ['Centrum', 'Galeria', 'Online']
produkty = ['A', 'B', 'C', 'D']
print(f"Kształt macierzy: {ceny.shape}") # (4, 3)

Kształt macierzy: (4, 3)


Zadanie 1a: Stwórz nowy array z cenami podniesionymi o 5% (inflacja).
Wyświetl wynik.

In [3]:
ceny_inflacja = ceny * 1.05
print("Ceny podniesione przez inflacje o 5%: ")
print(ceny_inflacja)

Ceny podniesione przez inflacje o 5%: 
[[ 31.4895  33.5895  30.4395]
 [ 52.4895  55.6395  50.3895]
 [ 15.7395  16.7895  14.6895]
 [104.9895 110.2395  99.7395]]


Zadanie 1b: Stwórz array z cenami po rabacie. Każdy sklep daje inny rabat:
Centrum 10%, Galeria 5%, Online 15%.

In [5]:
rabaty = np.array([0.10, 0.05, 0.15])
rabaty_cen = ceny * (1 - rabaty)
print("Ceny po rabacie dla sklepów: ")
print(rabaty_cen)

Ceny po rabacie dla sklepów: 
[[26.991  30.3905 24.6415]
 [44.991  50.3405 40.7915]
 [13.491  15.1905 11.8915]
 [89.991  99.7405 80.7415]]


Zadanie 1c: Oblicz koszt zakupu każdego produktu. Każdy produkt ma inną
marżę: A=30%, B=40%, C=25%, D=50%.

In [9]:
marza = np.array([[0.30], [0.40], [0.25], [0.50]])
marza_kolumna = marza.reshape(4,1)
koszt_zakupu = ceny / (1 + marza)
print("Koszt zakupu: ")
print(koszt_zakupu)

Koszt zakupu: 
[[23.06923077 24.60769231 22.3       ]
 [35.70714286 37.85       34.27857143]
 [11.992      12.792      11.192     ]
 [66.66       69.99333333 63.32666667]]


Zadanie 1d: Wyświetl najtańszy sklep dla każdego produktu.

In [10]:
najtansze = ceny.argmin(axis=1)
print("Najtansze sklepy (indeksy): ")
print(najtansze)

Najtansze sklepy (indeksy): 
[2 2 2 2]


Ćwiczenie 2: Reshape i łączenie danych (20 min)
Cel
Zmień kształt danych i połącz tablice z różnych źródeł.
Zadanie 2a — Reshape
# Dane miesięczne z jednego roku (flat)

In [11]:
dane_flat = np.array([120, 135, 98, 142, 167, 189, 201, 178, 156, 143, 198, 221])
kwartaly = dane_flat.reshape(4, 3)
print(f"Kwartały:\n{kwartaly}")
print(f"Suma per kwartał: {kwartaly.sum(axis=1)}")
print(f"Najlepszy kwartał: Q{kwartaly.sum(axis=1).argmax() + 1}")

Kwartały:
[[120 135  98]
 [142 167 189]
 [201 178 156]
 [143 198 221]]
Suma per kwartał: [353 498 535 562]
Najlepszy kwartał: Q4


Zadanie 2b — Stacking

In [12]:
# Dane z 3 oddziałów (osobne tablice)
warszawa = np.array([150, 160, 170, 180])
krakow = np.array([120, 130, 140, 150])
wroclaw = np.array([90, 100, 110, 120])
# Połącz w macierz (3 oddziały × 4 kwartały)
wszystkie = np.vstack([warszawa, krakow, wroclaw])
print(f"Wszystkie:\n{wszystkie}")
print(f"Suma per oddział: {wszystkie.sum(axis=1)}")
print(f"Suma per kwartał: {wszystkie.sum(axis=0)}")

Wszystkie:
[[150 160 170 180]
 [120 130 140 150]
 [ 90 100 110 120]]
Suma per oddział: [660 540 420]
Suma per kwartał: [360 390 420 450]


Zadanie 2c — Praktyczne (samodzielnie)

In [15]:
sprzedaz_flat = np.array([100, 200, 150, 300, 250, 180, 120, 220, 170, 310, 260, 190])
sprzedaz = sprzedaz_flat.reshape(6,2)
print(sprzedaz)

srednia_sprzedaz = sprzedaz.mean(axis=1)
print(srednia_sprzedaz)

zmiana = sprzedaz[:,1] - sprzedaz[:,0]
print(zmiana)

[[100 200]
 [150 300]
 [250 180]
 [120 220]
 [170 310]
 [260 190]]
[150. 225. 215. 170. 240. 225.]
[100 150 -70 100 140 -70]


Zadanie 2d — Flatten i concatenate
Masz macierz kwartałów z zadania 2a
1. Spłaszcz ją z powrotem do wektora (.flatten())
4
2. Dodaj dane z 13. miesiąca (wartość: 235) — np.concatenate()
Podpowiedź: np.concatenate([wektor, np.array([235])])

In [17]:
wektor = kwartaly.flatten()
print(wektor)

_miesiac13 =  np.concatenate([wektor, np.array([235])])
print(_miesiac13)

[120 135  98 142 167 189 201 178 156 143 198 221]
[120 135  98 142 167 189 201 178 156 143 198 221 235]


Ćwiczenie 3: Analiza danych finansowych (30 min)
Cel
Samodzielna analiza danych finansowych firmy z użyciem zaawansowanych op
eracji NumPy.

In [21]:
np.random.seed(2026)

# 8 pracowników, dane roczne
pracownicy = ['Anna', 'Jan', 'Ewa', 'Marek', 'Kasia', 'Piotr', 'Zofia', 'Tomek']
pensje = np.array([5500, 7200, 4800, 9100, 6300, 4200, 8500, 5800])
staz = np.array([3, 8, 2, 15, 5, 1, 12, 4])
oceny = np.array([4.2, 3.8, 4.5, 4.0, 4.7, 3.5, 4.3, 3.9])
# Sprzedaż miesięczna 4 produktów przez 6 miesięcy
produkty_nazwy = ['Laptop', 'Tablet', 'Smartfon', 'Akcesorium']
sprzedaz = np.random.randint(20, 200, size=(4, 6))
ceny_produktow = np.array([3500, 1800, 2500, 150])

Zadania
Zadanie 3a: Analiza wynagrodzeń


In [34]:
# 1. Oblicz średnią, medianę i odchylenie standardowe pensji
# Podpowiedź: pensje.mean(), np.median(pensje), pensje.std()
# 2. Wyświetl imiona osób zarabiających powyżej średniej
# Uwaga: pracownicy to lista — zamień na np.array(pracownicy), żeby użyć maski
# Podpowiedź: nazwy = np.array(pracownicy), potem nazwy[pensje > pensje.mean()]
# 3. Wyświetl imiona osób zarabiających poniżej mediany
# 4. Oblicz rozstęp (max- min) i rozstęp międzykwartylowy (IQR)
# Podpowiedź: IQR = np.percentile(pensje, 75)- np.percentile(pensje, 25)

srednia = pensje.mean()
print(srednia)
mediana = np.median(pensje)
odchylenie = pensje.std()

imiona = np.array(pracownicy)
maska_imiona = pensje > srednia
imiona_powyzej = imiona[maska_imiona]
print(imiona_powyzej)

maska_mediana = pensje < mediana
imiona_ponizej = imiona[maska_mediana]
print(imiona_ponizej)

rozstep = pensje.max() - pensje.min()
IQR = np.percentile(pensje, 75)- np.percentile(pensje, 25)
print(rozstep)
print(IQR)


6425.0
['Jan' 'Marek' 'Zofia']
['Anna' 'Ewa' 'Piotr' 'Tomek']
4900
2200.0


Zadanie 3b: System premii (np.where)

In [33]:
# Zasady premii:
#- ocena >= 4.5 → premia 2000 zł
#- ocena >= 4.0 → premia 1000 zł
#- ocena < 4.0 → premia 0 zł
# Podpowiedź: zagnieżdżony where:
# np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))
# Oblicz nowe wynagrodzenie (pensja + premia)
# Kto dostał najwyższą premię? Użyj argmax()

premia = np.where(oceny >= 4.5, 2000, np.where(oceny >= 4.0, 1000, 0))
print(premia)

nowe_wynagrodzenie = pensje + premia
print(nowe_wynagrodzenie)

#z uzyciem argmax
najwyz_premia = premia.argmax()
kto = imiona[najwyz_premia]
print("Najwyzsza premie dostał/ła: " + kto)

#poprawny wynik
max_premia = premia.max()
osoby_z_max = imiona[premia == max_premia]
print(osoby_z_max)



[1000    0 2000 1000 2000    0 1000    0]
[ 6500  7200  6800 10100  8300  4200  9500  5800]
Najwyzsza premie dostał/ła: Ewa
['Ewa' 'Kasia']


Zadanie 3c: Ranking (argsort)

In [37]:
# Posortuj pracowników wg pensji (od najwyższej)
# Podpowiedź: kolejnosc = np.argsort(pensje)[::-1]
# Wyświetl ranking: pozycja, imię, pensja, staż
# Podpowiedź: for i, idx in enumerate(kolejnosc, 1): ...

kolejnosc = np.argsort(pensje)[::-1]
print("Ranking pracowników od najwyższej: ")
for i, idx in enumerate(kolejnosc, 1):
    imię = imiona[idx]
    pensja = pensje[idx]
    staz_pracy = staz[idx]
    print(str(i) + "." + imię + " - Pensja: " + str(pensja) + "zł, Staż: " + str(staz_pracy) + " lat.")

Ranking pracowników od najwyższej: 
1.Marek - Pensja: 9100zł, Staż: 15 lat.
2.Zofia - Pensja: 8500zł, Staż: 12 lat.
3.Jan - Pensja: 7200zł, Staż: 8 lat.
4.Kasia - Pensja: 6300zł, Staż: 5 lat.
5.Tomek - Pensja: 5800zł, Staż: 4 lat.
6.Anna - Pensja: 5500zł, Staż: 3 lat.
7.Ewa - Pensja: 4800zł, Staż: 2 lat.
8.Piotr - Pensja: 4200zł, Staż: 1 lat.


Zadanie 3d: Korelacja

In [42]:
# Oblicz korelację: staż vs pensja
# Podpowiedź: np.corrcoef(staz, pensje)[0, 1]
# Oblicz korelację: staż vs ocena
# Który związek jest silniejszy? (wyższa wartość bezwzględna r)

korelacja_ = np.corrcoef(staz, pensje)[0, 1]
korelacja_staz_ocena = np.corrcoef(staz,oceny)[0,1]

print("korelacja staz vs pensja: " + str(korelacja_))
print("Korelacja staz vs oceny: " + str(korelacja_staz_ocena))
print("Silniejszy jest związek między stażem a pensją.")

korelacja staz vs pensja: 0.987862864584301
Korelacja staz vs oceny: 0.04198471605953068
Silniejszy jest związek między stażem a pensją.


Zadanie 3e: Analiza sprzedaży (broadcasting)

In [50]:
# Oblicz przychód: sprzedaz (4×6) * ceny_produktow (4,) — UWAGA na broadcasting!
# Problem: (4,6) * (4,) — nie pasuje! 6 != 4
# Rozwiązanie: ceny muszą być kolumną (4×1)
# Podpowiedź: ceny_kol = ceny_produktow.reshape(4, 1)
#przychod = sprzedaz * ceny_kol
# Który produkt przyniósł największy łączny przychód? (axis=1, argmax)
# Który miesiąc był najlepszy łącznie? (axis=0, argmax)
# Trend: porównaj pierwsze 3 miesiące vs ostatnie 3
# Podpowiedź: przychod[:, :3].sum() vs przychod[:, 3:].sum()

ceny_kol = ceny_produktow.reshape(4, 1)
przychod = sprzedaz * ceny_kol

najwiekszy_przychod = produkty_nazwy[przychod.sum(axis=1).argmax()]
print("Produkt który przyniósł największy łączny przychód to: " + najwiekszy_przychod)

najlepszy_miesiac = przychod.sum(axis=0).argmax() + 1
print("Najlepszy miesiąc to: " + str(najlepszy_miesiac))

trend1 = przychod[:,:3].sum()
trend2 = przychod[:,3:].sum()
print("Suma I: " + str(trend1))
print("Suma II: " + str(trend2))

Produkt który przyniósł największy łączny przychód to: Smartfon
Najlepszy miesiąc to: 2
Suma I: 2463950
Suma II: 2536500


Ćwiczenie 4: Generowanie danych (15 min)
Cel
Wygeneruj realistyczne dane biznesowe i przeanalizuj je.

In [51]:
np.random.seed(42)
# Wygeneruj dane o 100 klientach sklepu:
#- wiek: rozkład normalny, średnia 35, std 10, zaokrąglony do int, min 18
#- wydatki_miesiecznie: rozkład normalny, średnia 500, std 200, min 0
#- liczba_wizyt: rozkład Poissona, lambda=5
# Podpowiedź: np.clip() ogranicza wartości do zakresu
wiek = np.clip(np.random.normal(35, 10, 100).astype(int), 18, None)
wydatki = np.clip(np.random.normal(500, 200, 100), 0, None)
wizyty = np.random.poisson(5, 100)

Krok 2 — Analiza (samodzielnie)

In [67]:
# 1. Statystyki opisowe każdej zmiennej (mean, median, std, min, max)
# Podpowiedź: print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}")

print(f"Wiek — średnia: {wiek.mean():.1f}, mediana: {np.median(wiek):.1f}, std={wiek.std():.1f}, min={wiek.min()}, max={wiek.max()}")

# 2. Korelacja wiek vs wydatki

korelacja1 = round(np.corrcoef(wiek,wydatki)[0,1],2)
print("Wiek/wydatki: " + str(korelacja1))

# Podpowiedź: np.corrcoef(wiek, wydatki)[0, 1]
# 3. Korelacja wizyty vs wydatki

korelacja2 = round(np.corrcoef(wizyty, wydatki)[0,1],2)
print("Wizyty/wydatki: " + str(korelacja2))

# 4. Segmentacja klientów za pomocą np.where:
#- "WYSOKI" gdy wydatki > średnia + std
#
#- "NISKI" gdy wydatki < średnia- std- "ŚREDNI" w pozostałych przypadkach
# Podpowiedź: zagnieżdżony np.where (jak w zadaniu 3b)
# sr = wydatki.mean()
# sd = wydatki.std()
# segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr- sd, 'NISKI', 'ŚREDNI'))

sr = wydatki.mean()
sd = wydatki.std()
segment = np.where(wydatki > sr + sd, 'WYSOKI', np.where(wydatki < sr- sd, 'NISKI', 'ŚREDNI'))
#print(segment)

# 5. Ile klientów w każdym segmencie? Użyj np.unique(..., return_counts=True)

nazwy,liczniki = np.unique(segment, return_counts=True)
print("Liczba klientów w segmentach: ", dict(zip(nazwy,liczniki)))

Wiek — średnia: 33.6, mediana: 33.0, std=8.6, min=18, max=53
Wiek/wydatki: -0.12
Wizyty/wydatki: -0.16
Liczba klientów w segmentach:  {np.str_('NISKI'): np.int64(17), np.str_('WYSOKI'): np.int64(12), np.str_('ŚREDNI'): np.int64(71)}
